- name: Install graphite web
  apt: name=graphite-web update-cache=yes state=present

- name: configure graphite
  copy: src=local_settings.py dest=/etc/graphite

- command: 'chown -R _graphite: /usr/share/graphite-web/'

- name: initialise graphite database
  command: graphite-manage syncdb --noinput

- command: 'chown _graphite: /var/lib/graphite/graphite.db'

- apt: name=apache2 update-cache=yes state=present

- apt: name=libapache2-mod-wsgi state=present

- command: a2enmod headers

- command: a2dissite 000-default

- copy: src=apache2-graphite.conf dest=/etc/apache2/sites-available

- command: a2ensite apache2-graphite

- service: name=apache2 state=restarted

